name: animated_marker
description: Animate Google Maps markers smoothly between location updates.
version: 0.3.0
homepage: https://github.com/landxcape/animated_marker
repository: https://github.com/landxcape/animated_marker
issue_tracker: https://github.com/landxcape/animated_marker/issues
topics:
  - google-maps
  - marker-animation
  - map

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.14.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
